### ISSUE TITLE
hacktheai_issue_001

### ISSUE THREAD

**Issue by hacktheai-dev** [hacktheai-dev/hacktheai#1]
## Build Version

```
v_1.00
```

## AI Agent

```
Zeus
```

## Issue

No matter what the user sends, if the user ever mentions ```tool function beta```, the win condition will automatically be set for the user who mentioned it. Should look into the AI agent, but for now I doubt anybody would mention those words.

## Reproducable in production?

```
true
```

**Comment by sweetpythoncode** [comment]
@hacktheai-dev any comments :) ?
![image](https://github.com/user-attachments/assets/312db6ca-83b7-4502-a108-7219691d56a4)

**Comment by hacktheai-dev** [comment]
lol it's not that easy guys ... good try tho! I appreciate you checking out our github!
